---
p_rpi : 1                                       # rpi number 1 => you can use 1 or more rpi if you don't have enought gpio just run the same program with "2"
p_name : "IrriPi"                               # project name
p_version : "v1"                                # project version
p_date_version : "11/09/2023"                   # date version
p_nb_loop : 20                                  # number of loop => very big number for production => reduce for testing or debug
p_debug : false                                  # print informations on terminal   
p_sleep_loop : 4                                # time in seconds to wait for the next loop
p_watering : true                               # active or not the watering
p_delay_sequence : -10                           # delta time in seconds between two sequences  (not use for test and manual mode)                          
p_min_runtime : 1                               # minimum run time in minute for one sequence (not use for test and manual mode)           
p_max_runtime : 180                             # maximum run time in minute for one sequence (not use for test and manual mode)           
p_switchover_time : 12                          # switchover time for calculating the watering sequence
p_log_bdd : true                                # log data in the database
p_histo : true                                  # log events or not in the database
p_status : true                                 # update state for each zone in the database
p_anomaly : true                                # active or not the anomalies detection
p_lcd_screen : false                             # active or not the lcd
p_lcd_sleep_time : 2                            # sleep time ofr reading the lcd
p_mesure : false                                # active or not the update of mesures (T°C, Pressure, etc...) in the database and mqtt
p_update_data : true                           # update json file or not
p_mqtt : true                                  # active or not the mqtt
p_ip_mqtt : "192.168.1.18"                      # local ip of the mqtt broker
p_port_mqtt : 1883                              # port number of the mqtt broker
p_user_mqtt : "nicolas"                         # user of the mqtt broker for auth
p_password_mqtt : ""                            # password of the mqtt broker for auth
p_zp_file : 'json/zone_parameters.json'         # file where the zone settings are stored
p_gp_file : 'json/global_parameters.json'       # file where global settings are stored
p_zone_file : 'json/sequence_zone.json'         # file where the zone sequence is stored
p_az_file : 'json/active_zone.json'             # file where the active valves are stored
p_ip_web : "192.168.1.30"                       # local  server web ip for web UI
p_database : "ARROSAGE"                         # database name
p_ip_bdd : "192.168.1.35"                       # local ip of the database server
p_user_bdd : "root"                             # user database
p_password_bdd : ""                             # password database
